<?php
  include("aggregator.php");
?>
<!DOCTYPE html>

<html lang="bg">

<head>
<!-- Meta -->
<meta charset="utf-8" />
<meta name="author" content="Георги Д. Сотиров" />
<meta name="description" content="Лични страници на Георги Сотиров" />
<meta name="keywords" content="Георги Сотиров, лични страници, автобиография, проекти, албуми, речник" />
<meta name="copyright" content="2004-2020 Георги Д. Сотиров" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Лични страници на Георги Сотиров</title>
<!-- Stylesheets -->
<link rel="stylesheet" media="speech" title="По подразбиране" type="text/css" href="style/speech.css" />
<link rel="stylesheet" media="print, screen" title="По подразбиране" type="text/css" href="style/blue.css" />
<link rel="alternate stylesheet" media="print, screen" title="Сиво" type="text/css" href="style/gray.css" />
<!-- Icon -->
<link rel="icon" href="img/favicon" />
<link rel="shortcut icon" href="img/favicon"  />
<!-- Links -->
<link rel="author" href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E" />
<link rel="copyright" href="copyright" />
<link rel="search" href="search" />
<link rel="glossary" href="glossary" />
<link rel="up" href="index" title="Up" />
<link rel="alternate" type="text/html" href="index.en" hreflang="en" lang="en" title="Georgi Sotirov's Personal Pages" />
<link rel="alternate" type="application/atom+xml" href="http://gdsotirov-bg.blogspot.com/atom.xml" title="Дневника на Георги Сотиров" />
<!-- Scripts -->
<script src="js/sprintf.js"></script>
<script src="js/common.js"></script>
<script src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
</head>

<body>

<section id="Menu">
<h2>Начало</h2>
<nav id="MenuPage">
<ul>
<li><a accesskey="З" href="#About"><span class="u">З</span>а мен</a></li>
<li><a accesskey="Д" href="#Blog"><span class="u">Д</span>невник</a></li>
<li><a accesskey="А" href="cv/cv" title="Автобиография (нова страница)"><span class="u">А</span>втобиография</a></li>
<li><a accesskey="Л" href="personal" title="Още за мен"><span class="u">Л</span>ично</a></li>
<li><a accesskey="П" href="projects/" title="Проекти (нова страница)"><span class="u">П</span>роекти</a></li>
<li><a accesskey="В" href="#Contacts"><span class="u">В</span>ръзка</a></li>
<li><a accesskey="Г" href="#Propaganda">Пропа<span class="u">г</span>анда</a></li>
</ul></nav>
<nav id="MenuGeneral">
<ul>
<li><a accesskey="Р" href="glossary"><span class="u">Р</span>ечник</a></li>
<li><a accesskey="Т" href="search"><span class="u">Т</span>ърсене</a></li>
</ul></nav>
<nav id="MenuLang">
<ul>
<li><a accesskey="E" href="index.en" hreflang="en"><span class="u">E</span>nglish</a></li>
</ul></nav>
</section>

<header>
<h1>Лични страници на Георги Сотиров</h1>
</header>

<main>

<section id="About">
<h2 class="no_top_margin">За мен</h2>
<p class="texti">Добре дошли на личните ми страници. Тук можете да научите
повече за мен и начините за връзка с мен. Ще намерите някои от личните ми
проекти и ще можете да разгледате актуалната ми автобиография.</p>
<p class="texti">Аз съм инженер по специалност <a href="http://tu-sofia.bg/faculties/read/27">Компютърни
системи и технологии</a> от <a href="http://www.tu-sofia.bg/"><abbr
title="Технически Университет">ТУ</abbr> - София</a> и магистър по <a
href="http://ecatalog.nbu.bg/default.asp?V_Year=2012&amp;PageShow=programpresent&amp;P_Menu=generalinfo&amp;Fac_ID=4&amp;M_PHD=0&amp;P_ID=971">Бизнес
администрация</a> от <a href="https://www.nbu.bg/"><abbr title="Нов Български Университет">НБУ</abbr></a>.
Професионалните ми интересите и проектите ми са в областта на разработването
и пакетирането на програмно осигуряване, програмирането и релационните бази
от данни.</p>
<p class="texti">Интересувам се от астрономия и изследване на космоса. Обичам
да плувам и карам колело. В свободното си време вземам участие в отворени
проекти. Фен съм на <a href="https://www.formula1.com/" hreflang="en">Формула 1</a>
и <a href="https://www.lemans.org/" hreflang="en">Le Mans</a> и когато мога
посещавам съзтезания.</p>
</section>

<section id="Blog">
<h2>Дневник</h2>
<p>
<?php
  $aggregator = new CAggregateBlog("http://gdsotirov-bg.blogspot.com/feeds/posts/default", 10);
  $aggregator->setLang("bg");
  $aggregator->aggregate();
?>
</p>
<p class="align-right">
<a href="http://gdsotirov-bg.blogspot.com/">Архив</a>&nbsp;|&nbsp;<img alt="Емисия:" src="/icons/feed" title="Емисия" />&nbsp;<a
href="http://gdsotirov-bg.blogspot.com/feeds/posts/default" type="application/atom+xml">Atom</a></p>
</section>

<section id="Contacts">
<h2>Връзка с мен</h2>
<p class="text_left">Можете да се свържете с мен по електронна поща, чрез незабавни съобщения или социални мрежи.</p>

<h3>Е-поща</h3>
<ul id="contact_email">
<li><a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov%5Bin%5Ddir.bg%3E">gdsotirov[in]dir.bg</a></li>
<li><a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov%5Bin%5Dgmail.com%3E">gdsotirov[in]gmail.com</a></li>
</ul>

<h3>Незабавни съобщения, разговори и видео</h3>
<ul id="contact_icq">
<li><span style="float: left"><em>Skype</em>: gdsotirov (</span>
<div id="SkypeButton">
<script>
  Skype.ui({"name": "dropdown", "element": "SkypeButton", "participants": ["gdsotirov"]});
</script>
</div>)</li>
<li><em>Viber</em>: мобилният ми номер</li>
</ul>

<h3>Социални мрежи</h3>
<ul class="my-share-buttons">
<li><a href="https://www.facebook.com/gdsotirov/" title="Свързване в Facebook">
  <img alt="Свързаване в Facebook" src="/img/soc_fb" /></a></li>
<li><a href="https://twitter.com/gdsotirov" title="Следване в Twitter">
  <img alt="Следване в Twitter" src="/img/soc_tw" /></a></li>
<li><a href="https://www.linkedin.com/in/gdsotirov" title="Свързване в LinkedIn">
  <img alt="Свързване в LinkedIn" src="/img/soc_li" /></a></li>
</ul>

</section>

<section id="Propaganda">
<h2>Пропаганда</h2>
<!-- KDE -->
<p class="text_left">
<a href="http://www.kde.org/" hreflang="en">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48" /></a></p>
<p class="text_left">Тези страници са разработени изцяло в
<a href="http://www.kde.org/" hreflang="en">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left"><a href="http://kdewebdev.org/quanta/" hreflang="en"><img
alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88" /></a></p>
<p class="text_left">Кода на тези страници е написан на ръка в
<a href="http://kdewebdev.org/quanta/" hreflang="en">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left"><a href="https://www.gimp.org/" hreflang="en"><img
alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48" /></a></p>
<p class="text_left">Графиката по тези страници е създадена и/или редактирана с
<a href="https://www.gimp.org/" hreflang="en">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left"><a href="https://www.mozilla.org/bg/" hreflang="bg"><img
alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"  /></a></p>
<p class="text_left">Тези страници са разработени и изпитани в
<a href="https://www.mozilla.org/bg/" hreflang="bg">Mozilla</a>.</p>
</section>

</main>

<footer>
<hr />
<div id="Conformance">
<map id="ConformanceBar" name="ConformanceBar">
<p class="align-center">
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check/referer" hreflang="en">
<img alt="[Икона за валиден XHTML 1.0]" height="31" src="/img/valid-xhtml"
title="Валиден XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="http://jigsaw.w3.org/css-validator/check" hreflang="en">
<img alt="[Икона за валиден CSS]" height="31" src="/img/valid-css"
title="Валиден CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibilty -->
<a href="http://www.w3.org/WAI/WCAG1AAA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво Тройно-А, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Обяснение на съответствие с ниво Тройно-А" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" src="/img/unicode"
title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">Copyright &copy; 2004-2020 <a
href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">Георги Д. Сотиров</a>
<br /><a href="copyright">Всички права запазени</a></p>
</div>
</footer>

</body>
</html>
