<?php
  include("aggregator.php");
?>
<!DOCTYPE html>

<html lang="en">

<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="author" content="Georgi D. Sotirov">
<meta name="description" content="Georgi Sotirov's Personal Pages">
<meta name="keywords" content="Georgi Sotirov, personal pages, CV, projects, albums, glossary">
<meta name="copyright" content="2004-2024 Georgi D. Sotirov">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Georgi Sotirov's Personal Pages</title>
<!-- Stylesheets -->
<link rel="stylesheet" media="all" title="Default" type="text/css" href="style/speech.css">
<link rel="stylesheet" media="print, screen"  title="Default" type="text/css" href="style/blue.css">
<link rel="alternate stylesheet" media="print, screen" title="Gray" type="text/css" href="style/gray.css">
<!-- Icon -->
<link rel="icon" href="img/favicon">
<link rel="shortcut icon" href="img/favicon" >
<!-- Links -->
<link rel="author" href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@gmail.com%3E">
<link rel="copyright" href="copyright">
<link rel="search" href="search">
<link rel="glossary" href="glossary">
<link rel="up" href="index" title="Up">
<link rel="alternate" type="text/html" href="index.bg" hreflang="bg" lang="bg" title="Лични страници на Георги Сотиров">
<link rel="alternate" type="application/atom+xml" href="https://gdsotirov.blogspot.com/atom.xml" title="Georgi Sotirov's Blog">
<!-- Scripts -->
<script src="js/sprintf.js"></script>
<script src="js/common.js"></script>
</head>

<body>

<section id="Menu">
<h2>Home</h2>
<nav id="MenuPage">
<ul>
<li><a accesskey="A" href="#About"><span class="u">A</span>bout me</a></li>
<li><a accesskey="B" href="#Blog"><span class="u">B</span>log</a></li>
<li><a accesskey="V" href="cv/cv" title="CV (new page)">C<span class="u">V</span></a></li>
<li><a accesskey="P" href="personal" title="More about me"><span class="u">P</span>ersonal</a></li>
<li><a accesskey="J" href="projects/" title="Projects (new page)">Pro<span class="u">j</span>ects</a></li>
<li><a accesskey="C" href="#Contacts"><span class="u">C</span>ontacts</a></li>
<li><a accesskey="R" href="#Propaganda">P<span class="u">r</span>opaganda</a></li>
</ul></nav>
<nav id="MenuGeneral">
<ul>
<li><a accesskey="G" href="glossary"><span class="u">G</span>lossary</a></li>
<li><a accesskey="S" href="search"><span class="u">S</span>earch</a></li>
</ul></nav>
<nav id="MenuLang">
<ul>
<li><a accesskey="Б" href="index.bg" hreflang="bg"><span class="u">Б</span>ългарски</a></li>
</ul></nav>
</section>

<header>
<h1>Georgi Sotirov's Personal Pages</h1>
</header>

<main>

<section id="About">
<h2 class="no_top_margin">About me</h2>
<p class="texti">Welcome to my personal pages. Here you can learn
more about me and the ways to contact me. You'll find some of my personal
projects and you'll be able review my current CV.</p>
<p class="texti">I'm an engineer with major <a
href="https://tu-sofia.bg/faculties/specialties/27" target="_blank">Computer
systems and technologies</a> from <a href="https://tu-sofia.bg/" target="_blank">
<abbr title="Technical University">TU</abbr> of Sofia</a> and magister of <a
href="https://ecatalog.nbu.bg/default.asp?V_Year=2012&amp;PageShow=programpresent&amp;P_Menu=generalinfo&amp;Fac_ID=4&amp;M_PHD=0&amp;P_ID=971"
target="_blank">Business Administration</a> from <a href="https://www.nbu.bg/"
target="_blank"><abbr title="New Bulgarian University">NBU</abbr></a>.
My professional interests and projects are in the field of
software development and packaging, programming and relational
databases.</p>
<p class="texti">I'm interested in astronomy and space exploration. I Like
swimming and biking. In my spare time I participate in open projects.
I'm fan of <a href="https://www.formula1.com/"
target="_blank">Formula 1</a> and <a href="https://www.lemans.org/"
target="_blank">Le Mans</a> and when I can I'm visting races.</p>
</section>

<section id="Blog">
<h2>Blog</h2>
<p>
<?php
  $aggregator = new CAggregateBlog("https://gdsotirov.blogspot.com/feeds/posts/default", 10);
  $aggregator->setLang("en");
  $aggregator->aggregate();
?>
</p>
<p class="align-right">
<a href="https://gdsotirov.blogspot.com/" target="_blank">Archive</a>&nbsp;|&nbsp;<img alt="Feed:" src="/icons/feed" title="Feed">&nbsp;<a
href="https://gdsotirov.blogspot.com/feeds/posts/default" type="application/atom+xml">Atom</a></p>
</section>

<section id="Contacts">
<h2>Contacts</h2>
<p class="text_left">You can contact my by electronic mail, through
instant messaging or social networks.</p>

<h3>E-mail</h3>
<p><a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov%5Bin%5Dgmail.com%3E">gdsotirov[in]gmail.com</a></p>

<h3>Instant messaging</h3>
<ul id="contact_icq">
<li><em>Skype</em>: gdsotirov</li>
<li><em>Viber</em>: my mobile phone number</li>
</ul>

<h3>Social networks</h3>
<ul class="my-share-buttons">
<li><a href="https://www.facebook.com/gdsotirov/" title="Connect in Facebook"
target="_blank"><img alt="Connect in Facebook" src="/img/soc_fb"></a></li>
<li><a href="https://twitter.com/gdsotirov" title="Follow in Twitter"
target="_blank"><img alt="Follow in Twitter" src="/img/soc_tw"></a></li>
<li><a href="https://www.linkedin.com/in/gdsotirov" title="Connect in LinkedIn"
target="_blank"><img alt="Connect in LinkedIn" src="/img/soc_li"></a></li>
</ul>

</section>

<section id="Propaganda">
<h2>Propaganda</h2>
<!-- KDE -->
<p class="text_left">
<a href="https://www.kde.org/" target="_blank">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48"></a></p>
<p class="text_left">This site is developed entirely in
<a href="https://www.kde.org/" target="_blank">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left">
<a href="https://userbase.kde.org/Quanta" target="_blank">
<img alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88"></a></p>
<p class="text_left">Code of this site is handwritten in
<a href="https://userbase.kde.org/Quanta"
target="_blank">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left">
<a href="https://www.gimp.org/" target="_blank">
<img alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48"></a></p>
<p class="text_left">Graphics on this site created and edited with
<a href="https://www.gimp.org/" target="_blank">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left">
<a href="https://www.mozilla.org/en-US/" target="_blank">
<img alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"></a>&nbsp;<a
href="https://www.mozilla.org/en-US/firefox/" target="_blank">
<img alt="Mozilla Firefox logo" height="48" src="img/logo_firefox"
title="Mozilla Firefox" width="46"></a></p>
<p class="text_left">This site was initially developed and tested with
<a href="https://www.mozilla.org/en-US/" target="_blank">Mozilla</a>
and later on with <a href="https://www.mozilla.org/en-US/firefox/"
target="_blank">Mozilla Firefox</a>.</p>
</section>

</main>

<footer>
<hr>
<div id="Conformance">
<map id="ConformanceBar" name="ConformanceBar">
<p class="align-center">
<!-- Valid HTML 5 -->
<a href="https://validator.w3.org/check/referer" target="_blank">
<img alt="[Valid HTML 5 icon]" height="31" src="/img/valid-html5"
title="Valid HTML 5!" width="88"></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="https://jigsaw.w3.org/css-validator/check"
target="_blank"><img alt="[Valid CSS icon]" height="31"
src="/img/valid-css" title="Valid CSS!" width="88"></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibility -->
<a href="https://www.w3.org/WAI/WCAG1AAA-Conformance"
target="_blank"><img
alt="[Level Triple-A conformance icon, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Explanation of Level Triple-A Conformance" width="88"></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="https://www.unicode.org/" target="_blank">
<img alt="[Encoded in UTF-8 icon]" height="31" src="/img/unicode"
title="Encoded in UTF-8!" width="88"></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">Copyright &copy; 2004-2024 <a
href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@gmail.com%3E">Georgi D. Sotirov</a>
<br><a href="copyright">All rights reserved</a></p>
</div>
</footer>

</body>
</html>
