<?php
  print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  include("syndicate.php");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<meta http-equiv="Content-Type" content="test/html; charset=UTF-8" />
<meta name="author" content="Георги Д. Сотиров" />
<meta name="description" content="Лични страници на Георги Сотиров" />
<title>Лични страници на Георги Сотиров</title>
<link href="style/aural.css" media="aural" rel="stylesheet" title="Default" />
<link href="style/handheld.css" media="handheld" rel="stylesheet" title="Default" />
<link href="style/default.css" media="print, projection, screen, tv" rel="stylesheet" title="Default" />
<link rel="icon" href="img/favicon" />
<link rel="shortcut icon" href="img/favicon"  />
<link rel="author" href="mailto:Георги Сотиров &lt;gdsotirov@dir.bg&gt;" />
<link rel="copyright" href="copyright" />
<link rel="search" href="search" />
<link rel="glossary" href="glossary" />
<link rel="up" href="index" title="Up" />
<link rel="alternate" type="text/html" href="index.en.phtml" hreflang="en" lang="en" title="Georgi Sotirov's Personal Pages" />
<link rel="alternate" type="application/atom+xml" href="http://gdsotirov-bg.blogspot.com/atom.xml" title="Дневника на Георги Сотиров" />
<script src="js/sprintf.js" type="text/javascript"></script>
<script src="js/common.js" type="text/javascript"></script>
</head>

<body>

<div id="Menu" class="left">
<h2>Начало</h2>
<map id="MenuPage">
<p>
<a accesskey="З" href="#AboutMe"><span class="u">З</span>а мен</a>
<a accesskey="Д" href="#Blog"><span class="u">Д</span>невник</a>
<a accesskey="А" href="cv/cv"><span class="u">А</span>втобиография</a>
<a accesskey="П" href="projects/"><span class="u">П</span>роекти</a>
<a accesskey="А" href="/gallery/"><span class="u">А</span>лбуми</a>
<a accesskey="В" href="#Contacts"><span class="u">В</span>ръзка</a>
<a accesskey="Г" href="#Propaganda">Пропа<span class="u">г</span>анда</a>
</p></map>
<map id="MenuGeneral">
<p>
<a accesskey="Р" href="glossary"><span class="u">Р</span>ечник</a>
<a accesskey="Т" href="search"><span class="u">Т</span>ърсене</a>
</p></map>
<map id="MenuLang">
<p><a accesskey="E" href="index.en.phtml" hreflang="en"><span class="u">E</span>nglish</a>
</p></map>
</div>

<h1>Лични страници на Георги Сотиров</h1>

<div id="Content" class="right">
<div id="AboutMe">
<h2 class="no_top_margin">За мен</h2>
<p class="texti">Казвам се Георги Сотиров и това са моите лични страници.
Тук можете да намерите някои от моите проекти, да разгледате автобиографията
и албумите ми и въобще да се запознаете с мен.</p>
<p class="texti">Аз съм дипломиран инженер по специалност <a href="http://www.tu-sofia.bg/Bul/faculties/fksu/fksu-specialnosti.htm">Компютърни
системи и технологии</a> от <a href="http://www.tu-sofia.bg">Техническия Университет
- София</a>, степен Бакалавър. Интересите и проектите ми са в областта на
разработването на програмно осигуряване и програмирането. Интересувам се от
астрономия и изследване на космоса. В свободното си време вземам участие в
свободни проекти и обичам да гледам
<a href="http://www.formula1.com" hreflang="en">Формула 1</a>.</p>
</div>

<div id="Blog">
<h2>Дневник</h2>
<p>
<?php
  $syn = new CAgregateBlog("http://gdsotirov-bg.blogspot.com/atom.xml");
  $syn->agregate();
?>
</p>
<p class="align-right">
<a href="http://gdsotirov-bg.blogspot.com">Архив</a>&nbsp;|&nbsp;<img alt="Емисия:" src="/icons/feed" title="Емисия" />&nbsp;<a
href="http://gdsotirov-bg.blogspot.com/atom.xml" type="application/atom+xml"><img alt="XML Икона" src="/img/xml_feed" title="Feed" /></a></p>
</div>

<div id="Contacts">
<h2>Връзка с мен</h2>
<p class="text_left">Можете да се свържете с мен по</p>

<h3>Е-поща</h3>
<ul id="contact_email">
<li><a href="mailto:Георги Сотиров &lt;gdsotirov@dir.bg&gt;">gdsotirov@dir.bg</a></li>
<li><a href="mailto:Георги Сотиров &lt;gdsotirov@gmail.com&gt;">gdsotirov@gmail.com</a></li>
<li><a href="mailto:Георги Сотиров &lt;gdsotirov@yahoo.com&gt;">gdsotirov@yahoo.com</a> (Състояние:&nbsp;<img alt="Състояние на gdsotirov в Yahoo! Messenger" src="http://opi.yahoo.com/online?u=gdsotirov&amp;m=g&amp;t=1" />, <a href="http://edit.yahoo.com/config/set_buddygrp?.src=&amp;.cmd=a&amp;.bg=Friends&amp;.bdl=gdsotirov" hreflang="en">Добавяне</a>, <a href="http://edit.yahoo.com/config/send_webmesg?.target=gdsotirov" hreflang="en">Изпращане на съобщение</a>)</li>
<li><a href="mailto:Георги Сотиров &lt;gdsotirov@hotmail.com&gt;">gdsotirov@hotmail.com</a></li>
</ul>

<h3>ICQ</h3>
<ul id="contact_icq">
<li>148246257 (Състояние:&nbsp;<img alt="Състояние на ICQ номер 148246257" src="http://web.icq.com/whitepages/online?icq=148246257&amp;img=21" />)</li>
</ul>

<!-- ICQ Mesage Form
<form action="http://wwp.icq.com/scripts/WWPMsg.dll" id="ICQMsgForm"
method="post" onsubmit="javascript: return checkMsgBody();">
<fieldset>
<legend><img alt="&lt;ICQ icon&gt;" src="img/icq.png" />&nbsp;Формуляр за
изпращане на <span lang="en">ICQ</span> съобщение</legend>
<input alt="To" name="to" type="hidden" value="148246257" />
<input alt="From Your Web Page" name="subject" type="hidden" value="From Your Web Page" />

<div class="row">
<label for="from">
<span class="label">От:&nbsp;</span>
<span class="input"><input accesskey="O" alt="From" id="from" name="from"
maxlength="40" size="16" type="text" value="" /></span></label>
</div>
<div class="row">
<label for="fromemail">
<span class="label">Е-поща:&nbsp;</span>
<span class="input"><input accesskey="E" alt="Email" id="fromemail"
name="fromemail" maxlength="40" size="16" type="text" value="" /></span>
</label>
</div>
<div class="row">
<label for="body">
<span class="label">Съобщение:&nbsp;</span>
<span class="input"><input accesskey="M" alt="Message body" id="body"
name="body" maxlength="450" size="30" type="text" value="" /></span>
</label>
</div>
<div class="row">
<span class="label"></span>
<span class="input">
<input alt="Изпрати" name="Send" type="submit" value="Изпрати" /></span>
</div>
</fieldset></form>
ICQ Mesage Form -->

<h3>Skype</h3>
<ul>
<li>gdsotirov (<a href="callto://gdsotirov"><img alt="Skype me!&trade;" src="http://goodies.skype.com/graphics/skypeme_btn_small_lightgrey.gif" title="Започване на Skype обаждане към мен" /></a>)</li>
</ul>
</div>

<div id="Propaganda">
<h2>Пропаганда</h2>
<!-- KDE -->
<p class="text_left">
<a href="http://www.kde.org" hreflang="en">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48" /></a></p>
<p class="text_left">Тези страници са разработени изцяло в
<a href="http://www.kde.org" hreflang="en">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left"><a href="http://quanta.sf.net" hreflang="en"><img
alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88" /></a></p>
<p class="text_left">Кода на тези страници е написан на ръка в
<a href="http://quanta.sf.net" hreflang="en">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left"><a href="http://www.gimp.org" hreflang="en"><img
alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48" /></a></p>
<p class="text_left">Графиката по тези страници е създадена и/или редактирана с
<a href="http://www.gimp.org" hreflang="en">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left"><a href="http://www.mozilla.org" hreflang="en"><img
alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"  /></a></p>
<p class="text_left">Тези страници са разработени и изпитани в
<a href="http://www.mozilla.org" hreflang="en">Mozilla</a>.</p>
</div>
</div>

<div id="Footer">
<hr />
<div id="Conformance">
<map id="ConformanceBar">
<p class="align-center">
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check/referer" hreflang="en">
<img alt="[Икона за валиден XHTML 1.0]" height="31" src="/img/valid-xhtml"
title="Валиден XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="http://jigsaw.w3.org/css-validator/validator?uri=gsotirov79.ddns.homelan.bg/~gsotirov/&amp;usermedium=all" hreflang="en">
<img alt="[Икона за валиден CSS]" height="31" src="/img/valid-css"
title="Валиден CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibilty -->
<a href="http://www.w3.org/WAI/WCAG1AAA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво Тройно-А, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Обяснение на съответствие с ниво Тройно-А" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" src="/img/unicode"
title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">
Copyright &copy; 2004-2005 <a href="mailto:Георги Сотиров &lt;gdsotirov@dir.bg&gt;">Георги Д. Сотиров</a>
<br /><a href="copyright">Всички права запазени</a></p>
</div>
</div>

</body>
</html>
