<?php
  print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  include("agregator.php");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bg" lang="bg">

<head>
<!-- Meta -->
<meta http-equiv="Content-Type" content="test/html; charset=UTF-8" />
<meta name="author" content="Георги Д. Сотиров" />
<meta name="description" content="Лични страници на Георги Сотиров" />
<meta name="keywords" content="Георги Сотиров, лични страници, автобиография, проекти, албуми, речник" />
<meta name="copyright" content="2004-2017 Георги Д. Сотиров" />
<title>Лични страници на Георги Сотиров</title>
<!-- Stylesheets -->
<link rel="stylesheet" media="aural" title="По подразбиране" type="text/css" href="style/aural.css" />
<link rel="stylesheet" media="handheld" title="По подразбиране" type="text/css" href="style/handheld.css" />
<link rel="stylesheet" media="print, projection, screen, tv" title="По подразбиране" type="text/css" href="style/blue.css" />
<link rel="alternate stylesheet" media="print, projection, screen, tv" title="Сиво" type="text/css" href="style/gray.css" />
<!-- Icon -->
<link rel="icon" href="img/favicon" />
<link rel="shortcut icon" href="img/favicon"  />
<!-- Links -->
<link rel="author" href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E" />
<link rel="copyright" href="copyright" />
<link rel="search" href="search" />
<link rel="glossary" href="glossary" />
<link rel="up" href="index" title="Up" />
<link rel="alternate" type="text/html" href="index.en" hreflang="en" lang="en" title="Georgi Sotirov's Personal Pages" />
<link rel="alternate" type="application/atom+xml" href="http://gdsotirov-bg.blogspot.com/atom.xml" title="Дневника на Георги Сотиров" />
<!-- Scripts -->
<script src="js/sprintf.js" type="text/javascript"></script>
<script src="js/common.js" type="text/javascript"></script>
<script src="https://secure.skypeassets.com/i/scom/js/skype-uri.js" type="text/javascript"></script>
</head>

<body>

<div id="Menu">
<h2>Начало</h2>
<map id="MenuPage">
<p>
<a accesskey="З" href="#About"><span class="u">З</span>а мен</a>
<a accesskey="Д" href="#Blog"><span class="u">Д</span>невник</a>
<a accesskey="А" href="cv/cv" title="Автобиография (нова страница)"><span class="u">А</span>втобиография</a>
<a accesskey="Л" href="personal" title="Още за мен"><span class="u">Л</span>ично</a>
<a accesskey="П" href="projects/" title="Проекти (нова страница)"><span class="u">П</span>роекти</a>
<a accesskey="А" href="/gallery/" title="Албуми (нов сайт)"><span class="u">А</span>лбуми</a>
<a accesskey="В" href="#Contacts"><span class="u">В</span>ръзка</a>
<a accesskey="Г" href="#Propaganda">Пропа<span class="u">г</span>анда</a>
</p></map>
<map id="MenuGeneral">
<p>
<a accesskey="Р" href="glossary"><span class="u">Р</span>ечник</a>
<a accesskey="Т" href="search"><span class="u">Т</span>ърсене</a>
</p></map>
<map id="MenuLang">
<p><a accesskey="E" href="index.en" hreflang="en"><span class="u">E</span>nglish</a>
</p></map>
</div>

<div id="Header">
<h1>Лични страници на Георги Сотиров</h1>
</div>

<div id="Content">
<div id="About">
<h2 class="no_top_margin">За мен</h2>
<p class="texti">Казвам се Георги Сотиров и това са моите лични страници.
Тук можете да намерите някои от моите проекти, да разгледате автобиографията и албумите ми и
въобще да се запознаете с мен.</p>
<p class="texti">Аз съм дипломиран инженер по специалност <a href="http://tu-sofia.bg/faculties/read/27">Компютърни
системи и технологии</a> от <a href="http://www.tu-sofia.bg/">Техническия Университет
- София</a>, степен Бакалавър. Интересите и проектите ми са в областта на
разработването на програмно осигуряване и програмирането. Интересувам се от
астрономия и изследване на космоса. В свободното си време вземам участие в
отворени проекти и обичам да гледам <a href="https://www.formula1.com/" hreflang="en">Формула 1</a>.</p>
</div>

<div id="Blog">
<h2>Дневник</h2>
<p>
<?php
  $agregator = new CAgregateBlog("http://gdsotirov-bg.blogspot.com/feeds/posts/default", 10);
  $agregator->setLang("bg");
  $agregator->agregate();
?>
</p>
<p class="align-right">
<a href="http://gdsotirov-bg.blogspot.com/">Архив</a>&nbsp;|&nbsp;<img alt="Емисия:" src="/icons/feed" title="Емисия" />&nbsp;<a
href="http://gdsotirov-bg.blogspot.com/feeds/posts/default" type="application/atom+xml">Atom</a></p>
</div>

<div id="Contacts">
<h2>Връзка с мен</h2>
<p class="text_left">Можете да се свържете с мен по</p>

<h3>Е-поща</h3>
<ul id="contact_email">
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@dir.bg%3E">gdsotirovREMOVE@dir.bg</a></li>
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@gmail.com%3E">gdsotirovREMOVE@gmail.com</a></li>
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@yahoo.com%3E">gdsotirovREMOVE@yahoo.com</a></li>
</ul>

<h3>ICQ</h3>
<ul id="contact_icq">
<li>148246257 (Състояние:&nbsp;<img alt="Състояние на ICQ номер 148246257" src="http://web.icq.com/whitepages/online?icq=148246257&amp;img=21" />)</li>
</ul>

<h3>Skype</h3>
<ul>
<li>gdsotirov (<div id="SkypeButton">
  <script type="text/javascript">
    Skype.ui({"name": "dropdown", "element": "SkypeButton", "participants": ["gdsotirov"]});
  </script>
  </div>)</li>
</ul>
</div>

<div id="Propaganda">
<h2>Пропаганда</h2>
<!-- KDE -->
<p class="text_left">
<a href="http://www.kde.org/" hreflang="en">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48" /></a></p>
<p class="text_left">Тези страници са разработени изцяло в
<a href="http://www.kde.org/" hreflang="en">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left"><a href="http://kdewebdev.org/quanta/" hreflang="en"><img
alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88" /></a></p>
<p class="text_left">Кода на тези страници е написан на ръка в
<a href="http://kdewebdev.org/quanta/" hreflang="en">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left"><a href="https://www.gimp.org/" hreflang="en"><img
alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48" /></a></p>
<p class="text_left">Графиката по тези страници е създадена и/или редактирана с
<a href="https://www.gimp.org/" hreflang="en">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left"><a href="https://www.mozilla.org/bg/" hreflang="bg"><img
alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"  /></a></p>
<p class="text_left">Тези страници са разработени и изпитани в
<a href="https://www.mozilla.org/bg/" hreflang="bg">Mozilla</a>.</p>
</div>
</div>

<div id="Footer">
<hr />
<div id="Conformance">
<map id="ConformanceBar">
<p class="align-center">
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check/referer" hreflang="en">
<img alt="[Икона за валиден XHTML 1.0]" height="31" src="/img/valid-xhtml"
title="Валиден XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="http://jigsaw.w3.org/css-validator/check" hreflang="en">
<img alt="[Икона за валиден CSS]" height="31" src="/img/valid-css"
title="Валиден CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibilty -->
<a href="http://www.w3.org/WAI/WCAG1AAA-Conformance" hreflang="en">
<img alt="[Икона за съответствие с ниво Тройно-А, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Обяснение на съответствие с ниво Тройно-А" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Икона Кодирано в UTF-8]" height="31" src="/img/unicode"
title="Кодирано в UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">Copyright &copy; 2004-2017 <a
href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">Георги Д. Сотиров</a>
<br /><a href="copyright">Всички права запазени</a></p>
</div>
</div>

</body>
</html>
