<?php
  print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  include("agregator.php");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<!-- Meta -->
<meta http-equiv="Content-Type" content="test/html; charset=UTF-8" />
<meta name="author" content="Georgi D. Sotirov" />
<meta name="description" content="Georgi Sotirov's Personal Pages" />
<title>George Sotirov's Personal Pages</title>
<!-- Stylesheets -->
<link href="style/aural.css" media="aural" rel="stylesheet" title="Default" />
<link href="style/handheld.css" media="handheld" rel="stylesheet" title="Default" />
<link href="style/blue.css" media="print, projection, screen, tv" rel="stylesheet" title="Default" />
<link href="style/gray.css" media="print, projection, screen, tv" rel="alternate stylesheet" title="Gray" />
<!-- Icon -->
<link rel="icon" href="img/favicon"  />
<link rel="shortcut icon" href="img/favicon"  />
<!-- Links -->
<link rel="author" href="mailto:Georgi Sotirov &lt;gdsotirov@dir.bg&gt;" />
<link rel="copyright" href="copyright" />
<link rel="search" href="search" />
<link rel="glossary" href="glossary" />
<link rel="up" href="index" title="Up" />
<link rel="alternate" type="text/html" href="index.bg.phtml" hreflang="bg" lang="bg" title="Лични страници на Георги Сотиров" />
<link rel="alternate" type="application/atom+xml" href="http://gdsotirov.blogspot.com/atom.xml" title="Georgi Sotirov's Blog" />
<!-- Scripts -->
<script src="js/sprintf.js" type="text/javascript"></script>
<script src="js/common.js" type="text/javascript"></script>
</head>

<body>

<div id="Menu" class="left">
<h2>Home</h2>
<map id="MenuPage">
<p>
<a accesskey="A" href="#About"><span class="u">A</span>bout me</a>
<a accesskey="B" href="#Blog"><span class="u">B</span>log</a>
<a accesskey="V" href="cv/cv" title="CV (new page)">C<span class="u">V</span></a>
<a accesskey="P" href="personal" title="More about me"><span class="u">P</span>ersonal</a>
<a accesskey="J" href="projects/" title="Projects (new page)">Pro<span class="u">j</span>ects</a>
<a accesskey="B" href="/gallery/" title="Albums (new site)">Al<span class="u">b</span>lbums</a>
<a accesskey="C" href="#Contacts"><span class="u">C</span>ontacts</a>
<a accesskey="R" href="#Propaganda">P<span class="u">r</span>opaganda</a>
</p></map>
<map id="MenuGeneral">
<p>
<a accesskey="G" href="glossary"><span class="u">G</span>lossary</a>
<a accesskey="S" href="search"><span class="u">S</span>earch</a>
</p></map>
<map id="MenuLang">
<p><a accesskey="Б" href="index.bg.phtml" hreflang="bg"><span class="u">Б</span>ългарски</a>
</p></map>
</div>

<div id="Header">
<h1>Georgi Sotirov's Personal Pages</h1>
</div>

<div id="Content" class="right">
<div id="About">
<h2 class="no_top_margin">About me</h2>
<p class="texti">My name is Georgi Sotirov and this are my personal pages.
Here you can find some of my projects, to review my CV and my albums and get
familiar with me at all.</p>
<p class="texti">I'm diplomed engineer with major of <a href="http://www.tu-sofia.bg/Bul/faculties/fksu/fksu-specialnosti.htm">Computer
systems and technologies</a> from <a href="http://www.tu-sofia.bg">Technical
University of Sofia</a>, Bachelor degree. My interests and projects are in the
field of software development and programming. I'm interested in astronomy and
space exploration. In my spare time I participate in open projects and I love to
watch <a href="http://www.formula1.com" hreflang="en">Formula 1</a>.</p>
</div>

<div id="Blog">
<h2>Blog</h2>
<p>
<?php
  $agregator = new CAgregateBlog("http://gdsotirov.blogspot.com/atom.xml");
  $agregator->setLang("en");
  $agregator->agregate();
?>
</p>
<p class="align-right">
<a href="http://gdsotirov.blogspot.com">Archive</a>&nbsp;|&nbsp;<img alt="Feed:" src="/icons/feed" title="Feed" />&nbsp;<a
href="http://gdsotirov.blogspot.com/atom.xml" type="application/atom+xml">Atom</a></p>
</div>

<div id="Contacts">
<h2>Contacts</h2>
<p class="text_left">You can contact my by</p>

<h3>E-mail</h3>
<ul id="contact_email">
<li><a href="mailto:Georgi Sotirov &lt;gdsotirov_@dir.bg&gt;">gdsotirov_@dir.bg</a></li>
<li><a href="mailto:Georgi Sotirov &lt;gdsotirov_@gmail.com&gt;">gdsotirov_@gmail.com</a></li>
<li><a href="mailto:Georgi Sotirov &lt;gdsotirov_@yahoo.com&gt;">gdsotirov_@yahoo.com</a> (Status:&nbsp;<img alt="Yahoo! Messenger's gdsotirov Status" src="http://opi.yahoo.com/online?u=gdsotirov&amp;m=g&amp;t=1" />, <a href="http://edit.yahoo.com/config/set_buddygrp?.src=&amp;.cmd=a&amp;.bg=Friends&amp;.bdl=gdsotirov">Add contact</a>, <a href="http://edit.yahoo.com/config/send_webmesg?.target=gdsotirov">Send message</a>)</li>
<li><a href="mailto:Georgi Sotirov &lt;gdsotirov_@hotmail.com&gt;">gdsotirov_@hotmail.com</a></li>
</ul>
<p class="note">Note: Please, remove the unserscore before the @ sign to get
the real addresses.</p>

<h3>ICQ</h3>
<ul id="contact_icq">
<li>148246257 (Status:&nbsp;<img alt="ICQ's 148246257 Status" src="http://web.icq.com/whitepages/online?icq=148246257&amp;img=21" />)</li>
</ul>

<!-- ICQ Mesage Form
<form action="http://wwp.icq.com/scripts/WWPMsg.dll" id="ICQMsgForm"
method="post" onsubmit="javascript: return checkMsgBody();">
<fieldset>
<legend><img alt="&lt;ICQ icon&gt;" src="img/icq.png" />&nbsp;ICQ Message Form
</legend>
<input alt="To" name="to" type="hidden" value="148246257" />
<input alt="From Your Web Page" name="subject" type="hidden"
value="From Your Web Page" />

<div class="row">
<label for="from">
<span class="label"><span class="u">F</span>rom:&nbsp;</span>
<span class="input"><input accesskey="F" alt="From" id="from" name="from"
maxlength="40" size="16" type="text" value="" /></span></label>
</div>
<div class="row">
<label for="fromemail">
<span class="label"><span class="u">E</span>mail:&nbsp;</span>
<span class="input"><input accesskey="E" alt="Email" id="fromemail"
name="fromemail" maxlength="40" size="16" type="text" value="" /></span>
</label>
</div>
<div class="row">
<label for="body">
<span class="label"><span class="u">M</span>essage:&nbsp;</span>
<span class="input"><input accesskey="M" alt="Message body" id="body"
name="body" maxlength="450" size="30" type="text" value="" /></span>
</label>
</div>
<div class="row">
<span class="label"></span>
<span class="input">
<input alt="Send" name="Send" type="submit" value="Send" /></span>
</div>
</fieldset></form>
ICQ Mesage Form -->

<h3>Skype</h3>
<ul>
<li>gdsotirov (<a href="callto://gdsotirov"><img alt="Skype me!&trade;" src="http://goodies.skype.com/graphics/skypeme_btn_small_lightgrey.gif" title="Initatate a Skype call to me" /></a>)</li>
</ul>
</div>

<div id="Propaganda">
<h2>Propaganda</h2>
<!-- KDE -->
<p class="text_left">
<a href="http://www.kde.org" hreflang="en">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48" /></a></p>
<p class="text_left">This site is developed entirely in
<a class="text" href="http://www.kde.org" hreflang="en">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left"><a href="http://quanta.sf.net" hreflang="en"><img
alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88" /></a></p>
<p class="text_left">Code of this site is handwritten in
<a class="text" href="http://quanta.sf.net" hreflang="en">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left"><a href="http://www.gimp.org" hreflang="en"><img
alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48" /></a></p>
<p class="text_left">Graphics on this site created and/or edited with
<a class="text" href="http://www.gimp.org" hreflang="en">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left"><a href="http://www.mozilla.org" hreflang="en"><img
alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"  /></a></p>
<p class="text_left">This site is developed and tested with
<a class="text" href="http://www.mozilla.org" hreflang="en">Mozilla</a>.</p>
</div>
</div>

<div id="Footer">
<hr />
<div id="Conformance">
<map id="ConformanceBar">
<p class="align-center">
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check/referer" hreflang="en">
<img alt="[Valid XHTML 1.0 icon]" height="31" src="/img/valid-xhtml"
title="Valid XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="http://jigsaw.w3.org/css-validator/validator?uri=gsotirov79.ddns.homelan.bg/~gsotirov/&amp;usermedium=all" hreflang="en">
<img alt="[Valid CSS icon]" height="31" src="/img/valid-css"
title="Valid CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibilty -->
<a href="http://www.w3.org/WAI/WCAG1AAA-Conformance" hreflang="en">
<img alt="[Level Triple-A conformance icon, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Explanation of Level Triple-A Conformance" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" src="/img/unicode"
title="Encoded in UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">Copyright &copy; 2004-2006 <a href="mailto:Georgi Sotirov &lt;gdsotirov@dir.bg&gt;">Georgi D. Sotirov</a>
<br /><a href="copyright">All rights reserved</a></p>
</div>
</div>

</body>
</html>
