<?php
  print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  include("agregator.php");
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<!-- Meta -->
<meta http-equiv="Content-Type" content="test/html; charset=UTF-8" />
<meta name="author" content="Georgi D. Sotirov" />
<meta name="description" content="Georgi Sotirov's Personal Pages" />
<title>Georgi Sotirov's Personal Pages</title>
<!-- Stylesheets -->
<link rel="stylesheet" media="aural" title="Default" type="text/css" href="style/aural.css" />
<link rel="stylesheet" media="handheld" title="Default" type="text/css" href="style/handheld.css" />
<link rel="stylesheet" media="print, projection, screen, tv"  title="Default" type="text/css" href="style/blue.css" />
<link rel="alternate stylesheet" media="print, projection, screen, tv" title="Gray" type="text/css" href="style/gray.css" />
<!-- Icon -->
<link rel="icon" href="img/favicon"  />
<link rel="shortcut icon" href="img/favicon"  />
<!-- Links -->
<link rel="author" href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E" />
<link rel="copyright" href="copyright" />
<link rel="search" href="search" />
<link rel="glossary" href="glossary" />
<link rel="up" href="index" title="Up" />
<link rel="alternate" type="text/html" href="index.bg.phtml" hreflang="bg" lang="bg" title="Лични страници на Георги Сотиров" />
<link rel="alternate" type="application/atom+xml" href="http://gdsotirov.blogspot.com/atom.xml" title="Georgi Sotirov's Blog" />
<!-- Scripts -->
<script src="js/sprintf.js" type="text/javascript"></script>
<script src="js/common.js" type="text/javascript"></script>
<script src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js" type="text/javascript"></script>
</head>

<body>

<div id="Menu">
<h2>Home</h2>
<map id="MenuPage">
<p>
<a accesskey="A" href="#About"><span class="u">A</span>bout me</a>
<a accesskey="B" href="#Blog"><span class="u">B</span>log</a>
<a accesskey="V" href="cv/cv" title="CV (new page)">C<span class="u">V</span></a>
<a accesskey="P" href="personal" title="More about me"><span class="u">P</span>ersonal</a>
<a accesskey="J" href="projects/" title="Projects (new page)">Pro<span class="u">j</span>ects</a>
<a accesskey="B" href="/gallery/" title="Albums (new site)">Al<span class="u">b</span>lbums</a>
<a accesskey="C" href="#Contacts"><span class="u">C</span>ontacts</a>
<a accesskey="R" href="#Propaganda">P<span class="u">r</span>opaganda</a>
</p></map>
<map id="MenuGeneral">
<p>
<a accesskey="G" href="glossary"><span class="u">G</span>lossary</a>
<a accesskey="S" href="search"><span class="u">S</span>earch</a>
</p></map>
<map id="MenuLang">
<p><a accesskey="Б" href="index.bg.phtml" hreflang="bg"><span class="u">Б</span>ългарски</a>
</p></map>
</div>

<div id="Header">
<h1>Georgi Sotirov's Personal Pages</h1>
</div>

<div id="Content">
<div id="About">
<h2 class="no_top_margin">About me</h2>
<p class="texti">My name is Georgi Sotirov and this are my personal pages.
Here you can find some of my projects, to review my CV and my albums and get
familiar with me at all.</p>
<p class="texti">I'm diplomed engineer with major of <a href="http://www.tu-sofia.bg/Bul/faculties/fksu/fksu-specialnosti.htm">Computer
systems and technologies</a> from <a href="http://www.tu-sofia.bg">Technical
University of Sofia</a>, Bachelor degree. My interests and projects are in the
field of software development and programming. I'm interested in astronomy and
space exploration. In my spare time I participate in open projects and I love to
watch <a href="http://www.formula1.com" hreflang="en">Formula 1</a>.</p>
</div>

<div id="Blog">
<h2>Blog</h2>
<p>
<?php
  $agregator = new CAgregateBlog("http://gdsotirov.blogspot.com/feeds/posts/default", 10);
  $agregator->setLang("en");
  $agregator->agregate();
?>
</p>
<p class="align-right">
<a href="http://gdsotirov.blogspot.com">Archive</a>&nbsp;|&nbsp;<img alt="Feed:" src="/icons/feed" title="Feed" />&nbsp;<a
href="http://gdsotirov.blogspot.com/atom.xml" type="application/atom+xml">Atom</a></p>
</div>

<div id="Contacts">
<h2>Contacts</h2>
<p class="text_left">You can contact my by</p>

<h3>E-mail</h3>
<ul id="contact_email">
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@dir.bg%3E">gdsotirovREMOVE@dir.bg</a></li>
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@gmail.com%3E">gdsotirovREMOVE@gmail.com</a></li>
<li><a href="mailto:Georgi%20Sotirov%20%3CgdsotirovREMOVE@yahoo.com%3E">gdsotirovREMOVE@yahoo.com</a> (Status:&nbsp;<img alt="Yahoo! Messenger's gdsotirov Status" src="http://opi.yahoo.com/online?u=gdsotirov&amp;m=g&amp;t=1" />, <a href="http://edit.yahoo.com/config/set_buddygrp?.src=&amp;.cmd=a&amp;.bg=Friends&amp;.bdl=gdsotirov">Add contact</a>, <a href="http://edit.yahoo.com/config/send_webmesg?.target=gdsotirov">Send message</a>)</li>
</ul>

<h3>ICQ</h3>
<ul id="contact_icq">
<li>148246257 (Status:&nbsp;<img alt="ICQ's 148246257 Status" src="http://web.icq.com/whitepages/online?icq=148246257&amp;img=21" />)</li>
</ul>

<h3>Skype</h3>
<ul>
<li>gdsotirov (Status:&nbsp;<a href="skype:gdsotirov?call"><img alt="My status" height="20" src="http://mystatus.skype.com/smallclassic/gdsotirov" width="114" /></a>)</li>
</ul>
</div>

<div id="Propaganda">
<h2>Propaganda</h2>
<!-- KDE -->
<p class="text_left">
<a href="http://www.kde.org" hreflang="en">
<img alt="K Desktop Environment Logo" height="48" src="img/logo_kde"
title="The K Desktop Environment" width="48" /></a></p>
<p class="text_left">This site is developed entirely in
<a class="text" href="http://www.kde.org" hreflang="en">
<abbr class="expand" title="The K Desktop Environment">KDE</abbr>&trade;</a>.</p>
<!-- Quanta Plus -->
<p class="text_left"><a href="http://quanta.sf.net" hreflang="en"><img
alt="QuantaPlus Logo" height="48" src="img/logo_quantaplus"
title="QuantaPlus for KDE" width="88" /></a></p>
<p class="text_left">Code of this site is handwritten in
<a class="text" href="http://quanta.sf.net" hreflang="en">QuantaPlus</a>.</p>
<!-- The Gimp -->
<p class="text_left"><a href="http://www.gimp.org" hreflang="en"><img
alt="Gimp logo" height="48" src="img/logo_gimp"
title="The GNU Image Manipulation Program" width="48" /></a></p>
<p class="text_left">Graphics on this site created and/or edited with
<a class="text" href="http://www.gimp.org" hreflang="en">
<abbr class="expand" title="The GNU Image Manipulation Program">The Gimp
</abbr></a>.</p>
<!-- Mozilla -->
<p class="text_left"><a href="http://www.mozilla.org" hreflang="en"><img
alt="Mozilla logo" height="48" src="img/logo_mozilla" title="Mozilla"
width="133"  /></a></p>
<p class="text_left">This site is developed and tested with
<a class="text" href="http://www.mozilla.org" hreflang="en">Mozilla</a>.</p>
</div>
</div>

<div id="Footer">
<hr />
<div id="Conformance">
<map id="ConformanceBar">
<p class="align-center">
<!-- Valid XHTML 1.0 -->
<a href="http://validator.w3.org/check/referer" hreflang="en">
<img alt="[Valid XHTML 1.0 icon]" height="31" src="/img/valid-xhtml"
title="Valid XHTML 1.0!" width="88" /></a>&nbsp;
<!-- Valid CSS 2.1 -->
<a href="http://jigsaw.w3.org/css-validator/check" hreflang="en">
<img alt="[Valid CSS icon]" height="31" src="/img/valid-css"
title="Valid CSS!" width="88" /></a>&nbsp;
<!-- WAI WCAG 1.0 AA Compatibilty -->
<a href="http://www.w3.org/WAI/WCAG1AAA-Conformance" hreflang="en">
<img alt="[Level Triple-A conformance icon, W3C-WAI WCAG 1.0]"
height="31" src="/img/wai-wcag-1.0-3a"
title="Explanation of Level Triple-A Conformance" width="88" /></a>&nbsp;
<!-- UTF-8 Encoded -->
<a href="http://www.unicode.org/" hreflang="en">
<img alt="[Encoded in UTF-8 icon]" height="31" src="/img/unicode"
title="Encoded in UTF-8!" width="88" /></a>
</p></map>
</div>

<div id="Copyright">
<p class="copyright">Copyright &copy; 2004-2006 <a href="mailto:Georgi%20Sotirov%20%3Cgdsotirov@dir.bg%3E">Georgi D. Sotirov</a>
<br /><a href="copyright">All rights reserved</a></p>
</div>
</div>

</body>
</html>
